name: app-name

replicaCount: 1

deployment: {}
# deployment example
# deployment: 
#   containers:
#     example-app:
#       name: example-app
#       image:
#         repository: example-app
#         tag: latest
#   dnsConfig:
#     options:
#       - name: ndots
#         value: "2"

container:
  image:
    repository: repository_name/image
    tag: tag

global:
  imagePullPolicy: IfNotPresent

EnableMutilpleIngress: false
#EnableMutilpleIngress: true
#ingress:
#  internal-ingress:
#    annotations:
#      kubernetes.io/ingress.class: alb
#    rules:
#      - host:
#        http:
#          paths:
#          - backend:
#              serviceName: example
#              servicePort: 80
#            path: /health_check
#  external-ingress:
#    annotations:
#      kubernetes.io/ingress.class: alb
#    rules:
#      - host:
#        http:
#          paths:
#          - backend:
#              serviceName: example
#              servicePort: 80
#            path: /health_check

pdb:
  # If you just set "enable: true", default will set to "minAvailable: 50%" unless you have set other parameters.
  enable: false
  # Note: You can specify only one of maxUnavailable and minAvailable in a single PodDisruptionBudget, and if you setting both will only set maxUnavailable.
  # minAvailable: 50%
  # maxUnavailable: 50%

# autoscaling/v1 block
# hpa:
#   minReplicas: 1
#   maxReplicas: 2
#   targetCPUUtilizationPercentage: 60

# autoscaling/v2beta2 block
# hpav2:
#   minReplicas: 1
#   maxReplicas: 2
#   # k8s hpav2 native only support cpu and memory
#   Resource:
#     - name: cpu
#       value: 60
#     - name: memory
#       value: 100Mi
#   # setting external mertics
#   External:
#     - metricName: shop-nc-alb-request
#       # type support Value and AverageValue
#       type: Value
#       value: 10

# ExternalMetric:
#   name: shop-nc-alb-request
#   # queries setting please reference AWS cloudwatch api document link:
#   # https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_GetMetricData.html#API_GetMetricData_Examples
#   queries:
#     # Note: id can't use "-"
#     - id: shop_nc_alb_request
#       metricNamespace: AWS/ApplicationELB
#       metricName: RequestCount
#       metricsDimensions:
#         - name: LoadBalancer
#           value: app/397da054-core-shopnc-5edd/d8f7dcbb27908840
#       period: 60
#       stat: Sum
#       unit: Count